### PR TITLE
Added positioning options based on MovieClip data

### PR DESCRIPTION
**Pull request by JonathanTremblay**
Version 1.0.4 - Added positioning of sprites based on original MovieClips positions. - Added an option to use the MovieClip original pivot (from a Starling formed XML). - Added support to import empty frames from MovieClip.

### CODE REVIEW

**Comment by prankard** [comment]
Hey, thanks for this. I've attempted this before, but eventually gave up and went on to other things (hence the custompivot hack/fix).

I've had a look at the code. and tested it with some sprites from Adobe Flash CS6 (old I know) but currently the new pivot point code doesn't work. You can find it in the /Tests folder of this repo along with the .fla that I'm trying to export the sprite from.
I think on the later version of Adobe Animate, produces slightly different looking XML files. Another user tried to add this pivot fix already and I uploaded it and it broke everything.

Firstly, in my opinion, the extra options like pivot override should be removed. They were only added due to the fact I couldn't import them previously.

A question about your code:
1. 'useSpriteAutoAlignMode' and 'useXMLPivot' use two different pivots in the XML: "pivotX" and "frameX". I've seen "frameX" but not "pivotX" is this a new export XML node? Or just something a user can add?
The reference documentation for frameX and frameY I'm looking at is [here](https://doc.starling-framework.org/v2.3/starling/textures/TextureAtlas.html)

And can you link me to a generated file with the 'isFirstNode' check also as I do not have an example of that.

Thanks,

James

**Comment by JonathanTremblay** [comment]
Hi James,

The `frameX` and `frameY` attributes are related to the trim option (those attributes represent the offset of an individual image in relation to the movieclip full dimensions).

The `pivotX` and `pivotY` attributes are related to the movieclip pivot (those attributes represent the offset of the full movieclip in relation to the movieclip registration point). Pivot data is not described in the Starling documentation, but it has been around for a few years.

I have looked at your test XML files... It appears that Flash CS6 did not generate Starling XML pivot. I think that it was added with the first CC version, back in 2013 (I found a reference about it here: https://github.com/Gamua/Starling-Framework/issues/445). Official pivot support was added to the Starling framework number 2.3 (https://github.com/Gamua/Starling-Framework/blob/master/CHANGELOG.md#version-23---2017-12-18).

I added your test folder to my fork, with some new CC2019 generated XML files. Here's the line with the pivot data produced by CC2019:
`<SubTexture name="Movieclip0000" x="0" y="0" width="50" height="50" pivotX="25" pivotY="25"/>`

I'm not sure that I understand your last question about 'isFirstNode'. That boolean is there to optimize the code execution when the user manually selects a pivot (e.g. Top-Right). It allows the manual pivot to be calculated only once. The code would work without it, it would only be slightly slower. Your question made me look again at this mechanism, I then realized that there was a bug when there was many subtextures with different sizes. So I just pushed a new version to my fork with an added a line of code to correct this problem (isFirstNode is now back to true for each subtexture).

By the way, I would suggest leaving the pivot manual override functionality, at least for now. I guess it may still be useful for people using Sparrow formatted files (or files generated with CS6).

Another thought: maybe we could reduce the number of Debug.Log, to clarify the process. I can do that if you are OK with this idea.

Thank you for your interest!

**Comment by prankard** [comment]
Thanks for taking the time to generate the Adobe CC starling sprite sheet.

With your amend I had an issue with the way the pivot point worked with the old sprites I was generating with CS6.
I've gone ahead and uploaded a version I think works to a new branch on my github.

Thanks to your pivot change, I've taken the time to implement a new animation importer, which also helps visualise quickly if the new pivots are working (a feature I wanted to add when I originally made this a long time ago).

I need to test with some irregular pivots which I will get around to doing tomorrow. I have a newer version of Adobe Animate at work to ensure it all still works.

I changed the logic and working a fair bit.
The way I though was easiest was:

```
Pivot:
If we have a sprite xml pivot, use the xml pivot (unless forced overwritten)

Trim:
if the sprite is trimmed, then it has:
frameX, frameY, frameWidth, frameHeight
If so, the pivot needs to be adjusted to account for the blank space (forced or otherwise)

Apply pivot
```

The only feature I've removed is that the pivot is always based on movieclip rectangle. Not the individual sprite rectangle.

I didn't want to confuse my users with too many options, and I think it's a fair assumption that whatever they generate in Adobe Animate, we will try to keep it the same as in Unity.

**Comment by JonathanTremblay** [comment]
I do like your ideas to improve the interface. Importing the pivot by default is simple but effective! 

I also really like your new feature to create animations. However, if someone uses a sprite sheet containing many different movieclips, those are all joined in one long animation. I think that it would be more useful if separate animations and separate gameobjects could be created for each subtexture.

I tested your new version with different sprite sheets. It worked well with many sprite sheets. But I found a bug when I tested some movieclips with changing dimensions: the pivot is then positioned at a wrong location. To help you see the problem, I added a sprite sheet named «explosion» to my fork. In the movieclip, I placed a small red circle to show the pivot target location. If you try to import this sprite sheet with your most recent version, the pivot will be very far from its target. I did not try to find the problem in the code. Let me know if you need more details about this bug. I am happy to help!

**Comment by prankard** [comment]
Thanks for the example. It was really helpful.

Yes, it's been a while since I've done flash and seen the export option.
The animation clips are a good idea. To make them a new gameobject, we have to make a new animation controller for them all is a bit overboard by default, but of course we should separate out the animation into different animation clips.
Maybe have an option to generate animation controllers... not sure yet. I'll see how it goes.
I appears we can separate out the texture's by name to grab the different animations so it should be fairly simple.

I've gone ahead and updated the code, it's in a very messy state but I think it could be working. I've tested it working with a few animations with various pivot points.

**Comment by JonathanTremblay** [comment]
Hi James. 

Nice work, we are almost done! I tested your new version with a few other sprite sheets.

I found 2 problems:

1. The x axis was perfect, but the y axis was not right in some cases.
2. When a clip had empty frames, it created some Unity errors, because the pivot was NaN.

I fixed both problems. Please check my new commit: «[Bug Fix: y pivot and empty frames](https://github.com/prankard/FlashSpriteSheetImporter/pull/1/commits/d6afe0f66ea6070dc07f8c3739c7f75b91861599)»

I also added a new sprite sheet for test purposes (it includes empty frames).

By the way, we have a good work capacity with our different time zones! :-)

**Comment by prankard** [comment]
Hey, sorry I've been busy lately so not been optimising our time zones.

I've just tested your code and of course it looks good now :)
Thanks for the update. I'll try and merge it in the next day or so (and I'll add the new animation clip splitting) and then after that go ahead and push it to the Unity Asset Store.

Thanks for you help.

**Comment by JonathanTremblay** [comment]
Hi James,
How are you doing with the clip splitting project? Let me know when you are ready, I will be happy to help you test it!

**Comment by prankard** [comment]
Thanks for the reminder, I've been busy as of late.
I think I've pushed the splitting of multiple animations (Tests/WalkingPeople.png) is working
Animations are generated and added to the same controller, but not linked with a transition as we don't know how the user wants to animate these different movieclips, but the animations are generated.

Maybe I should add another option asking if they want different animation controllers. Although if we keep adding more features, we'll never be done.

**Comment by prankard** [comment]
Found a bug when importing frames without a sequence, it will now handle that.
If you try to make an animation with no sequence found, it will just make it one big animation to prevent multiple animations being created

**Comment by JonathanTremblay** [comment]
Hi James,

Good news... I made a few tests, without any bug discovery:
• I tested with a sprite sheet containing different actions for a single character.
• I tested with different movieclips containing empty frames.. 
•  I tested with different FPS settings.

Then... I realised that the new multiple clips functionality increased the risk of overwriting files. So I added some code to reduce that risk (it creates a subfolder for animations and adds '-Generated' to the animator controller). I also rewrote the ReadMe to clarify instructions for new users. Let me know what you think about those changes.

Thanks!

**Comment by prankard** [comment]
Merged into master.
Folder for the generated movieclips seems like a good idea :)
And thanks for testing also.
I'll just upload today to the asset store, should be live in the next few days.

**Comment by JonathanTremblay** [comment]
Excellent, I just saw the new version in the asset store! The updated demo video is a nice touch.

Let me know if some bugs are found or if you want help with other future functions. It was fun working with you!

Thanks.

________________________________
De : James Prankard <notifications@github.com>
Envoyé : 9 avril 2019 06:12
À : prankard/FlashSpriteSheetImporter
Cc : Jonathan TREMBLAY; Author
Objet : Re: [prankard/FlashSpriteSheetImporter] Added positioning options based on MovieClip data (#1)


Merged into master.
Folder for the generated movieclips seems like a good idea :)
And thanks for testing also.
I'll just upload today to the asset store, should be live in the next few days.

**Comment by prankard** [comment]
Yep, it was approved earlier than expected.
Again, thanks for the feedback and improvements :)

**Pull request merged**
